apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      imagePullSecrets:
      - name: harbor-secret
      containers:
      - name: story
        image: harbor.bahur/node-app/nodejs-app:simple
        env:
        - name: STORY_FOLDER
          value: 'story' 
        volumeMounts:
        - mountPath: /app/story
          name: story-volume
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
      - name: story-volume
        persistentVolumeClaim:
          claimName: host-pvc

